name: jacoco

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew test
      - name: Print TOKEN
        run: echo ${{ secrets.TOKEN }}
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacocoReport/test/jacocoTestReport.xml
          token: ${{ secrets.TOKEN }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50
